language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5"
  - "3.6-dev"
  - "nightly"
 
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -v -r requirements/build.txt
  - pip install coveralls
# command to run tests
script: py.test -v

after_success:
  coveralls
